language: python

sudo: false

python:
  - 3.4
  - 3.3
  - 2.7
  - 2.6

install:
  - pip install -r tests/requirements.py

script: nosetests --with-coverage --cover-package=./italian_vip_says/italian_vip_says

after_success: codecov
